### ISSUE TITLE
IOError: [Errno 2] No such file or directory: ','

### ISSUE THREAD

**Issue by lammh** [orioncleaver/FastCoref#1]
File "/home/FastCoref/readers.py", line 48, in read_a_book
for line in open(file, 'r'):
IOError: [Errno 2] No such file or directory: ','

**Comment by lammh** [comment]
python dyref.py  --s data/slate_data/alicesadventures.txt.annotation  --books  data/slate_data/alicesadventures.txt
[dynet] random seed: 1325154459
[dynet] allocating memory: 512MB
[dynet] memory allocation done.
Traceback (most recent call last):
  File "dyref.py", line 462, in <module>
    main(args)
  File "dyref.py", line 431, in main
    nn.read_books(format_, args)
  File "dyref.py", line 48, in read_books
    self.books = readers.read_normal_books(args.books)
  File "/home/FastCoref/readers.py", line 68, in read_normal_books
    book_dict[key] = read_a_book(path_dict[key])
  File "/home/FastCoref/readers.py", line 48, in read_a_book
    for line in open(file, 'r'):
IOError: [Errno 2] No such file or directory: ','
